version: '3.8'
services:
  postgres:
    image: yobasystems/alpine-postgres:16.1
    restart: always
    container_name: nestBD
    environment:
      - POSTGRES_USER=sammy
      - POSTGRES_PASSWORD=your_password
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  nest-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-api
    restart: always
    ports:
      - 3000:3000
      - 3001:3001
    depends_on:
      - postgres
    env_file:
      - .env

volumes:
  postgres:
