version: '3.3'
services:
  postgres:
    image: yobasystems/alpine-postgres:16.1
    restart: unless-stopped
    container_name: nestBD
    environment:
      - POSTGRES_USER=sammy
      - POSTGRES_PASSWORD=your_password
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  backend:
    image: andrey121992/monopoly-backend:latest
    container_name: backend-monopoly
    restart: unless-stopped
    ports:
      - 3000:3000
      - 3001:3001
    depends_on:
      - postgres
    env_file:
      - .env

  frontend:
    container_name: frontend-monopoly
    image: andrey121992/monopoly-frontend:latest
    restart: unless-stopped
    ports:
      - '80:80'
    depends_on:
      - postgres
      - backend

volumes:
  postgres:
