version: '3.8'
services:
  postgres:
    image: postgres:10.3
    restart: always
    environment:
      - POSTGRES_USER=sammy
      - POSTGRES_PASSWORD=your_password
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  postgres:

  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: nest-docker-postgres
  #   environment:
  #     - PORT=${PORT}
  #   ports:
  #     - '3000:3000'
  #   depends_on:
  #     - db
  #   volumes:
  #     - ./src:/app/src